"""Integration tests for LocalNginxAssetRepository signed URLs.

These tests spin up a real Nginx container using testcontainers and verify
that signed URLs generated by the Python library are accepted or rejected
by Nginx's ``ngx_http_secure_link_module``.

Prerequisites
-------------
* Docker must be running on the host that executes these tests.
* No manual ``docker compose`` setup is required — testcontainers manages the
  container lifecycle automatically.

Secret used in tests
--------------------
The Nginx config (``nginx-secure-link-test.conf``) and the repository config
in the fixtures both use ``"test-secret-key"`` as the shared secret.  This is
intentionally a weak value — **never use it in production**.

Marks
-----
Tests are marked with ``pytest.mark.integration`` so they can be excluded from
fast unit-test runs::

    # Run only unit tests (skip Docker):
    pytest -m "not integration"

    # Run everything including integration tests:
    pytest
"""

from __future__ import annotations

import time
from pathlib import Path

import httpx
import pytest

from granite_assets.enums import AssetVisibility
from granite_assets.exceptions import AssetAccessNotSupportedError
from granite_assets.models import AssetSaveRequest, LocalNginxAssetRepositoryConfig
from granite_assets.repositories.local_nginx import LocalNginxAssetRepository

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_TEST_SECRET = "test-secret-key"
_NGINX_CONF = Path(__file__).parent / "nginx-secure-link-test.conf"

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture(scope="session")
def assets_dir(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """Shared temp directory mounted into the Nginx container as /srv/assets.

    pytest creates temp directories with mode 0o700 (owner-only) for security,
    but the Nginx worker inside the container runs as a different UID and
    therefore cannot traverse them.  We explicitly set world-readable/executable
    permissions so that Nginx can serve files from this directory.
    """
    root = tmp_path_factory.mktemp("nginx-assets")
    root.chmod(0o755)
    (root / "public").mkdir(mode=0o755, exist_ok=True)
    (root / "private").mkdir(mode=0o755, exist_ok=True)
    return root


@pytest.fixture(scope="session")
def nginx_container(assets_dir: Path):  # type: ignore[return]
    """Start a real Nginx container and yield its base URL.

    The container is shared across the whole test session (``scope="session"``)
    to avoid the overhead of starting a new container for every test.

    The two host directories are mounted read-write so that test fixtures can
    write asset files directly and Nginx serves them immediately.

    Yields:
        str — Base URL of the container, e.g. ``"http://localhost:32768"``.
    """
    from testcontainers.core.container import DockerContainer
    from testcontainers.core.wait_strategies import LogMessageWaitStrategy

    container = (
        DockerContainer("nginx:alpine")
        .with_volume_mapping(str(_NGINX_CONF), "/etc/nginx/nginx.conf", "ro")
        .with_volume_mapping(str(assets_dir), "/srv/assets", "rw")
        .with_exposed_ports(80)
        # nginx:alpine logs "ready for start up" just before accepting connections.
        .waiting_for(LogMessageWaitStrategy("ready for start up"))
    )

    with container:
        host = container.get_container_host_ip()
        port = container.get_exposed_port(80)
        yield f"http://{host}:{port}"


@pytest.fixture()
def repo(nginx_container: str, assets_dir: Path) -> LocalNginxAssetRepository:
    """Repository instance configured to talk to the running Nginx container.

    ``base_url`` uses the dynamically assigned host port so the URL paths
    (including ``$uri`` in the Nginx token) remain consistent.
    """
    cfg = LocalNginxAssetRepositoryConfig(
        storage_path=str(assets_dir),
        base_url=f"{nginx_container}/assets",
        public_prefix="public",
        private_prefix="private",
        secure_link_secret=_TEST_SECRET,
        secure_link_ttl_seconds=60,
        create_directories=True,
    )
    return LocalNginxAssetRepository(cfg)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _save(
    repo: LocalNginxAssetRepository, key: str, visibility: AssetVisibility
) -> None:
    repo.save(
        AssetSaveRequest(
            key=key,
            source=f"content of {key}".encode(),
            content_type="text/plain",
            visibility=visibility,
        )
    )
    # pytest's tmp_path directories have mode 0o700; newly created subdirectories
    # and files inherit restrictive permissions.  Make everything world-readable
    # so the Nginx container user can traverse and serve the files.
    storage = Path(repo._cfg.storage_path)
    for path in storage.rglob("*"):
        path.chmod(0o755 if path.is_dir() else 0o644)


# ---------------------------------------------------------------------------
# Public asset tests — no token needed
# ---------------------------------------------------------------------------


@pytest.mark.integration
def test_public_asset_accessible_without_token(
    repo: LocalNginxAssetRepository,
) -> None:
    """A public asset must be downloadable via its permanent URL."""
    key = "integration/hello.txt"
    _save(repo, key, AssetVisibility.PUBLIC)
    access = repo.build_public_url(key)
    assert access.is_permanent

    response = httpx.get(access.url, timeout=5)
    assert response.status_code == 200
    assert b"integration/hello.txt" in response.content


@pytest.mark.integration
def test_public_asset_url_has_no_expiry(
    repo: LocalNginxAssetRepository,
) -> None:
    key = "integration/public-no-expiry.txt"
    _save(repo, key, AssetVisibility.PUBLIC)
    access = repo.build_public_url(key)
    assert access.expires_at is None


# ---------------------------------------------------------------------------
# Private asset — signed URL accepted by Nginx
# ---------------------------------------------------------------------------


@pytest.mark.integration
def test_private_asset_signed_url_returns_200(
    repo: LocalNginxAssetRepository,
) -> None:
    """A valid signed URL must be served by Nginx with 200 OK."""
    key = "integration/secret.txt"
    _save(repo, key, AssetVisibility.PRIVATE)
    access = repo.build_download_url(key)

    assert access.expires_at is not None  # must have an expiry
    assert "md5=" in access.url
    assert "expires=" in access.url

    response = httpx.get(access.url, timeout=5)
    assert response.status_code == 200
    assert b"integration/secret.txt" in response.content


@pytest.mark.integration
def test_private_asset_signed_url_has_expiry(
    repo: LocalNginxAssetRepository,
) -> None:
    key = "integration/has-expiry.txt"
    _save(repo, key, AssetVisibility.PRIVATE)
    access = repo.build_download_url(key)
    assert access.expires_at is not None
    assert not access.is_permanent


@pytest.mark.integration
def test_private_asset_signed_url_custom_ttl(
    repo: LocalNginxAssetRepository,
) -> None:
    """A custom TTL should be reflected in the ``expires`` query param."""
    key = "integration/custom-ttl.txt"
    _save(repo, key, AssetVisibility.PRIVATE)

    before = int(time.time())
    access = repo.build_download_url(key, ttl_seconds=7200)
    after = int(time.time())

    assert access.expires_at is not None
    expires_ts = int(access.expires_at.timestamp())
    assert before + 7200 <= expires_ts <= after + 7200


# ---------------------------------------------------------------------------
# Private asset — tampered / missing token rejected
# ---------------------------------------------------------------------------


@pytest.mark.integration
def test_private_asset_without_token_returns_403(
    repo: LocalNginxAssetRepository,
) -> None:
    """Accessing a private asset without a token must return 403 Forbidden."""
    key = "integration/no-token.txt"
    _save(repo, key, AssetVisibility.PRIVATE)

    # Build the bare URL without query parameters.
    base = repo._cfg.base_url.rstrip("/")
    prefix = repo._cfg.private_prefix
    url = f"{base}/{prefix}/{key}"

    response = httpx.get(url, timeout=5)
    assert response.status_code == 403


@pytest.mark.integration
def test_private_asset_tampered_token_returns_403(
    repo: LocalNginxAssetRepository,
) -> None:
    """A signed URL with a tampered token must be rejected with 403."""
    key = "integration/tampered.txt"
    _save(repo, key, AssetVisibility.PRIVATE)
    access = repo.build_download_url(key)

    # Replace the md5 token with garbage while keeping the expires param.
    tampered_url = access.url.replace(
        access.url.split("md5=")[1].split("&")[0],
        "AAAAAAAAAAAAAAAAAAAAAAAA",
    )
    response = httpx.get(tampered_url, timeout=5)
    assert response.status_code == 403


@pytest.mark.integration
def test_private_asset_expired_url_returns_410(
    repo: LocalNginxAssetRepository,
) -> None:
    """A signed URL with an expiry in the past must return 410 Gone."""
    key = "integration/expired.txt"
    _save(repo, key, AssetVisibility.PRIVATE)

    # Generate a URL with TTL = -10 s (already expired).
    access = repo.build_download_url(key, ttl_seconds=-10)
    response = httpx.get(access.url, timeout=5)
    assert response.status_code == 410


# ---------------------------------------------------------------------------
# resolve_access
# ---------------------------------------------------------------------------


@pytest.mark.integration
def test_resolve_access_private_signed(
    repo: LocalNginxAssetRepository,
) -> None:
    """resolve_access on a private asset returns a valid signed URL."""
    key = "integration/resolve-private.txt"
    _save(repo, key, AssetVisibility.PRIVATE)
    access = repo.resolve_access(key)

    assert not access.is_permanent
    response = httpx.get(access.url, timeout=5)
    assert response.status_code == 200


@pytest.mark.integration
def test_resolve_access_public(
    repo: LocalNginxAssetRepository,
) -> None:
    """resolve_access on a public asset returns a permanent URL."""
    key = "integration/resolve-public.txt"
    _save(repo, key, AssetVisibility.PUBLIC)
    access = repo.resolve_access(key)

    assert access.is_permanent
    response = httpx.get(access.url, timeout=5)
    assert response.status_code == 200


# ---------------------------------------------------------------------------
# No-secret fallback (unit-style, no Docker needed)
# ---------------------------------------------------------------------------


def test_private_url_without_secret_raises(tmp_path: Path) -> None:
    """When secure_link_secret is None, URL methods raise
    AssetAccessNotSupportedError."""
    cfg = LocalNginxAssetRepositoryConfig(
        storage_path=str(tmp_path),
        base_url="http://localhost/assets",
        secure_link_secret=None,
        create_directories=True,
    )
    repo = LocalNginxAssetRepository(cfg)
    repo.save(
        AssetSaveRequest(
            key="priv.txt",
            source=b"x",
            content_type="text/plain",
            visibility=AssetVisibility.PRIVATE,
        )
    )
    with pytest.raises(AssetAccessNotSupportedError):
        repo.build_download_url("priv.txt")

    with pytest.raises(AssetAccessNotSupportedError):
        repo.resolve_access("priv.txt")
